### ISSUE TITLE
Can´t log in with this mod

### ISSUE THREAD

**Issue by KaikiFather** [Umbra999/VRC-NoMoreAnalytics#2]

**Comment by Umbra999** [comment]
then you prolly got HWID banned before, this has nothing to do with login at all

**Comment by KaikiFather** [comment]
I got HWID banned before on other machines, not this. When i put the release DLL on mods, I can't go through the login screen just as the video shows. When i remove your mod, works fine.

https://streamable.com/hvz9i2

If I'm bothering you with this let me know and i'll stop

**Comment by Umbra999** [comment]
idk, works for me and others. you might have a injection method/maps which are not supported, as i see you use EACMelon, idk if it works with that because im using my own injection method.
